# Generated by Django 4.0.3 on 2022-03-28 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone'),
        ),
    ]
