# Generated by Django 4.0.3 on 2022-05-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_4',
        ),
    ]
