# Generated by Django 4.0.3 on 2022-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media/category'),
        ),
    ]
