# Generated by Django 4.0.3 on 2022-03-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorystatus',
            options={'ordering': ['pk', 'name'], 'verbose_name_plural': 'category status'},
        ),
    ]
