# Generated by Django 4.0.3 on 2022-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media/category'),
        ),
    ]
