# Generated by Django 4.0.3 on 2022-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productallfilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productallfilter',
            field=models.ManyToManyField(to='product.productallfilter'),
        ),
    ]
