# Generated by Django 4.0.3 on 2022-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_status_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='market_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
