# Generated by Django 4.0.3 on 2022-04-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_doller'),
    ]

    operations = [
        migrations.CreateModel(
            name='filtermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanal', models.CharField(blank=True, max_length=50, null=True)),
                ('xard', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='product.product')),
            ],
        ),
    ]
