# Generated by Django 4.0.3 on 2022-03-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mgpiksel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
