# Generated by Django 4.0.3 on 2022-03-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_evailable_product_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='CategoryStatus',
        ),
        migrations.AlterModelOptions(
            name='categorystatus',
            options={'ordering': ['pk', 'name'], 'verbose_name_plural': 'CategoryStatus'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='categorystatus',
        ),
    ]
