# Generated by Django 4.0.3 on 2022-03-15 05:25

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_categorystatus_delete_categorystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category'),
        ),
    ]
