# Generated by Django 4.0.3 on 2022-03-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_available_product_evailable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vailable',
        ),
    ]
