# Generated by Django 4.0.3 on 2022-04-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productallfilter_product_productallfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productallfilter',
            options={'ordering': ['pk', 'name'], 'verbose_name_plural': 'filter'},
        ),
    ]
