# Generated by Django 4.0.3 on 2022-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_filtermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodel',
            name='pikcel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
