# Generated by Django 4.0.3 on 2022-04-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_status_categorystatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorystatus',
        ),
        migrations.AddField(
            model_name='product',
            name='categorystatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categorystatus'),
        ),
    ]
