# Generated by Django 4.0.3 on 2022-04-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_categorystatus_product_categorystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorystatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.categorystatus'),
            preserve_default=False,
        ),
    ]
