# Generated by Django 4.0.3 on 2022-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/firs/'),
        ),
    ]
