# Generated by Django 4.0.3 on 2022-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_categorystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorystatus',
        ),
        migrations.AddField(
            model_name='product',
            name='categorystatus',
            field=models.ManyToManyField(to='product.categorystatus'),
        ),
    ]
