# Generated by Django 4.0.3 on 2022-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_categorystatus_product_categorystatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorystatus',
            options={'ordering': ['pk', 'name'], 'verbose_name_plural': 'CategoryStatuses'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorystatus',
            new_name='categorystatuses',
        ),
    ]
