# Generated by Django 4.0.3 on 2022-05-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productallfilter',
            new_name='productallfilterr',
        ),
    ]
