# Generated by Django 4.0.3 on 2022-05-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_productallfilter_product_productallfilterr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productallfilterr',
            new_name='productallfilter',
        ),
    ]
