# Generated by Django 4.0.3 on 2022-04-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_alter_children_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'ordering': ['pk', 'name'], 'verbose_name_plural': 'categories'},
        ),
    ]
