# Generated by Django 4.0.3 on 2022-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_filterproduct_children1_filterproduct_children2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilter',
            name='name',
        ),
        migrations.AddField(
            model_name='productfilter',
            name='fIlterproduct',
            field=models.ManyToManyField(to='filter.filterproduct'),
        ),
    ]
