# Generated by Django 4.0.3 on 2022-04-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_alter_children_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'ordering': ['pk', 'name'], 'verbose_name_plural': 'productfilter'},
        ),
    ]
