# Generated by Django 4.0.3 on 2022-04-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_remove_productfilter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterproduct',
            name='children',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children1',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children2',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children3',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children4',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children5',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children6',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children7',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children8',
        ),
        migrations.RemoveField(
            model_name='filterproduct',
            name='children9',
        ),
    ]
