# Generated by Django 4.0.3 on 2022-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_remove_filterproduct_children_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='filterproduct',
            name='children',
            field=models.ManyToManyField(to='filter.children'),
        ),
    ]
