# Generated by Django 4.0.3 on 2022-04-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_children_filterproduct_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterproduct',
            old_name='children',
            new_name='childrens',
        ),
    ]
