# Generated by Django 4.0.3 on 2022-04-11 09:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('filter', '0006_rename_children_filterproduct_childrens'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterproduct',
            name='categories',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productcategory', to='product.category'),
        ),
        migrations.AddField(
            model_name='filterproduct',
            name='categorystatuses',
            field=models.ManyToManyField(blank=True, to='product.categorystatus'),
        ),
        migrations.DeleteModel(
            name='Productfilter',
        ),
    ]
