# Generated by Django 4.0.3 on 2022-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolov', '0002_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Yaratildi'), (2, "To'landi"), (3, 'Bekor qilindi')], default=1),
        ),
    ]
