# Generated by Django 4.0.3 on 2022-04-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0002_remove_rasmadd_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasmImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banneradd')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Banner.rasmadd')),
            ],
        ),
    ]
