# Generated by Django 4.0.3 on 2022-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.AddField(
            model_name='refund',
            name='phone',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
